Feat: create global styles and variables, create theme store
Power-Rangers-3/Front-end pull request #29
Opened 2023-02-04 20:11 UTC by demyankov

2023-02-04 20:31 UTC, pyropetrick requested changes

2023-02-04 20:31 UTC, pyropetrick commented on src/pages/MainLayout/MainLayout.tsx
> +import { themeSelector } from 'store/features/theme/theme.selector';
добавь селектор в index.ts файл стора
и лучше наверн селекторы хранить отдельно в сторе в папке selectors) ну на мой взгляд)

2023-02-04 20:31 UTC, pyropetrick commented on src/pages/MainLayout/MainLayout.tsx
> +export function MainLayout() {
и мы вроде договорились через стрелочные функции компоненты создавать)

2023-02-04 20:31 UTC, pyropetrick commented on src/store/features/theme/theme.selector.ts
> +import { RootState } from 'store/types/types';
поправь тут тож импорт, он должен быть из store

2023-02-04 20:31 UTC, pyropetrick commented on src/store/features/theme/theme.slice.ts
> +    themeVariant: 'Light' as ThemeVariant,
почему бы просто initial state не создать как отдельную переменную? и сразу можно будет убрать as )

2023-02-05 06:13 UTC, andrey-kudinov approved these changes

2023-02-05 14:56 UTC, pyropetrick approved these changes

2023-02-05 15:01 UTC, merged