Registration form
Power-Rangers-3/Front-end pull request #30
Opened 2023-02-06 14:27 UTC by demyankov

2023-02-06 15:05 UTC, andrey-kudinov reviewed
Я так понимаю ПР ещё не закончен
Оставлю несколько комментариев

2023-02-06 15:05 UTC, andrey-kudinov commented on src/components/RegistrationForm/data/regularExpressions.ts
> +export const EMAIL_PATTERN =
👍

2023-02-06 15:05 UTC, andrey-kudinov commented on src/components/RegistrationForm/UI/FormButton/FormButton.tsx
> +  <button
Для этой кнопки точно нужен отдельный компонент? 🤔
Одно дело рендерить элемент `<button className="соотвествующие классф"></button>`
Другое дело сам компонент
Плюс это больше кода, дополнительные типы

2023-02-06 18:33 UTC, pyropetrick requested changes

2023-02-07 20:17 UTC, pyropetrick requested changes

2023-02-07 20:17 UTC, pyropetrick commented on src/components/RegistrationForm/registrationForm.tsx
> +import { useForm } from 'react-hook-form';
сам компонент с большой буквы) RegistrationForm*

2023-02-07 20:17 UTC, pyropetrick commented on src/components/RegistrationForm/api/userRegistration.ts
> +  return axios.post(apiPath, querryParams);
может через thunk с помощью redux-toolkit это лучше сделаем, но уже на след спринте я думаю)

2023-02-07 20:17 UTC, pyropetrick commented on src/pages/HomePage/HomePage.tsx
> +export const HomePage = () => <RegistrationForm />;
сделай мб отдельную страничку для регистрации) там роут есть ) просто чтобы показать функционал перехода допустим)

2023-02-08 05:47 UTC, andrey-kudinov requested changes

2023-02-08 05:47 UTC, andrey-kudinov commented on package.json
> +    "@mui/material": "^5.11.7",
Здесь нам material ui точно нужна?

2023-02-08 05:47 UTC, andrey-kudinov commented on src/components/RegistrationForm/UI/Input/Input.tsx
> +      {label ? <label htmlFor={id}>{label}</label> : null}
Используй лучше `&&` так как альтернатива только `null`

2023-02-08 05:47 UTC, andrey-kudinov commented on src/components/RegistrationForm/UI/Input/Input.tsx
> +        {Icon && iconStart ? (
Тоже самое

2023-02-08 05:47 UTC, andrey-kudinov commented on src/components/RegistrationForm/UI/Input/input.styles.module.scss
> +  .inputWrapper {
Тебе не нужна вложенность классов, это лишь увеличит специфичность и имя класса, но не решит никакой проблемы, так у нас модули и проблем с изоляцией стилей нет

2023-02-08 05:47 UTC, andrey-kudinov commented on src/components/RegistrationForm/registrationForm.styles.module.scss
> +  .inputGroupWrapper {
Так же здесь тоже не нужна вложенность

2023-02-08 11:00 UTC, PrimkY approved these changes

2023-02-08 11:02 UTC, merged