Header
Power-Rangers-3/Front-end pull request #31
Opened 2023-02-07 16:47 UTC by Sivilenok

2023-02-07 17:02 UTC, pyropetrick requested changes

2023-02-07 17:02 UTC, pyropetrick commented on src/router/router.tsx
> -import { HomePage } from 'pages';
тут тож верни

2023-02-07 17:02 UTC, pyropetrick commented on src/store/selectors/userSelector.ts
> +export const getUserAuth = (state: RootState) => state.user;
не очень подходит тогда название функции,, если так, то тогда state.user.isAuth на выходе должно быть
или же getUser, если так оставлять)

2023-02-07 17:02 UTC, pyropetrick commented on src/styles/globalStyles.ts
> +    list-style: none;
в ul)

2023-02-07 18:31 UTC, pyropetrick approved these changes
исправь только момент с альтом ) от меня апрув)

2023-02-07 18:31 UTC, pyropetrick commented on src/components/Header/Header.tsx
> +          <img src={logoIcon} className={styles.logo} alt={logoIcon} />
альт надо бы поправить на "TownSend logo"

2023-02-07 20:33 UTC, merged

2023-02-08 05:33 UTC, andrey-kudinov reviewed
ПР уже замерджен (
По возможности отмечайте меня когда кидаете ссылки на ПР чтобы я мог своевременно посмотреть

2023-02-08 05:33 UTC, andrey-kudinov commented on src/Styles.module.css
> +}/*# sourceMappingURL=Styles.module.css.map */
Нам нужны этот файл и файл чуть ниже в проекте?
Вроде их можно безболезненно удалить

2023-02-08 05:33 UTC, andrey-kudinov commented on src/assets/index.ts
> +import logoIcon from './icons/logo.svg';
Вроде вот так в одну строчку должно сработать
Вместо двух
`export { logoIcon as default } from "./icons/logo.svg";`

2023-02-08 05:33 UTC, andrey-kudinov commented on src/components/Header/Header.tsx
> +      <div className={styles.header__container}>
Тебе не нужно использовать `БЭМ` при использовании `модулей`
Это будет как лишние усложнение кода
Можно использовать короткие названия - `container`, `title`, `description` и тп

2023-02-08 05:33 UTC, andrey-kudinov commented on src/components/Header/Header.tsx
> +        <nav className={styles.header__nav}>
Хорошая семантика, молодец 👍

2023-02-08 05:33 UTC, andrey-kudinov commented on src/components/Header/Header.tsx
> +          <div className={styles.header__buttonWrapper}>
`wrapper` для нескольких кнопок - тогда во множественном числе
button**s**Wrapper

2023-02-08 05:33 UTC, andrey-kudinov commented on src/components/Header/styles.module.css
> +}/*# sourceMappingURL=styles.module.css.map */
У нас по всей видимости компилится `css map`
Нам нужно посмотреть как мы можем его убрать
В `sass cli` есть команды типа `--no-source-map`
Другое дело что мы можем не иметь доступ к этой команде так как она под капотом `CRA`

2023-02-14 20:18 UTC, Sivilenok commented on src/assets/index.ts
> +import logoIcon from './icons/logo.svg';
не я его делала, не поняла для чего он, решила не трогать на всякий)

2023-02-14 20:19 UTC, Sivilenok commented on src/Styles.module.css
> +}/*# sourceMappingURL=Styles.module.css.map */
я его не делала, не поняла зачем он и решила не трогать на всякий)

2023-02-14 20:20 UTC, Sivilenok commented on src/assets/index.ts
> +import logoIcon from './icons/logo.svg';
буду знать, спасибо)

2023-02-14 20:20 UTC, Sivilenok commented on src/components/Header/Header.tsx
> +      <div className={styles.header__container}>
поняла

2023-02-14 20:21 UTC, Sivilenok commented on src/components/Header/Header.tsx
> +        <nav className={styles.header__nav}>
благодарю)

2023-02-14 20:21 UTC, Sivilenok commented on src/components/Header/Header.tsx
> +          <div className={styles.header__buttonWrapper}>
точно! забыла)