Header adaptive
Power-Rangers-3/Front-end pull request #38
Opened 2023-02-18 17:04 UTC by Sivilenok

2023-02-20 06:14 UTC, demyankov commented on src/components/MenuNav/styles.module.scss
> +    display: flex;
дублирование

2023-02-20 06:14 UTC, demyankov commented on src/components/MenuNav/styles.module.scss
> +  align-items: center;
Может я не прав, но я бы использовал переменные, так как это дает возможность легко и быстро везде изменить стили.

2023-02-20 06:14 UTC, demyankov commented on src/components/MenuNav/styles.module.scss
> +  height: 56px;
Надо ли фиксировать размеры. На мой взгляд паддингов достаточно. Если придется увеличить текст в кнопке, то могут быть проблемы при фиксированных рамерах

2023-02-20 06:14 UTC, demyankov commented on src/components/MenuNav/styles.module.scss
> +    width: 172px;
Тоже самое по поводу размеров

2023-02-20 06:14 UTC, demyankov commented on src/components/MenuNav/styles.module.scss
> +    background-color: #000000;
переменная

2023-02-20 06:14 UTC, demyankov commented on src/components/MenuNav/styles.module.scss
> +    @include breakpoint(md) {
лучше удали))

2023-02-20 06:14 UTC, demyankov commented on src/components/MenuNav/styles.module.scss
> +      background: #4c4c4c;
переменная

2023-02-20 06:14 UTC, demyankov commented on src/components/MenuNav/styles.module.scss
> +      background: #b3b3b3;
переменная

2023-02-20 20:23 UTC, andrey-kudinov requested changes
Отличная работа, Севиль! Молодец!
Однако, есть несколько моментов, с помощью которых можно улучшить твой код
Посмотри пж в комментариях

2023-02-20 20:23 UTC, andrey-kudinov commented on package.json
> +    "styled-components": "^5.3.6",
Нам точно нужен `styled-components`
Я бы не добавлял его

2023-02-20 20:23 UTC, andrey-kudinov commented on src/components/Header/Header.tsx
> +      {width && width <= 768  ? (
То что можно сделать с помощью `css` лучше делать с помощью `css`
Так будет более хороший перфоманс

2023-02-20 20:23 UTC, andrey-kudinov commented on src/components/MenuNav/MenuNav.tsx
> +        {width && width > 768 && (
Я думаю здесь так же можно с помощью `css` сделать

2023-02-20 20:23 UTC, andrey-kudinov commented on src/components/MenuNav/styles.module.scss
> +      justify-content: space-between;
странно что `хаски` и `stylelint` это не отлавливают (
видимо сломались

2023-02-20 20:23 UTC, andrey-kudinov commented on src/hooks/useWindowSize.ts
> +  height: number | undefined;
Лучше использовать вот такой синтаксис, он более короткий
`height?: number`

2023-02-20 20:23 UTC, andrey-kudinov commented on src/hooks/useWindowSize.ts
> +    window.addEventListener('resize', handleResize);
К сожалению у слушателя изменения размеров так себе перфоманс
Я бы предложил от него отказаться и использовать `css` там где это возможно
У `css` отличный перфоманс
Если нужны следить за размерами, я бы предложил смотреть в сторону `Observer`

2023-02-20 20:23 UTC, andrey-kudinov commented on src/styles/shared/variables.ts
> +export enum BREAKPOINT {
Я бы не советовал использовать `enum` так как их нет в обычном `JS` и они с большим трудом компилируются из `TS` в `JS`

2023-02-22 19:06 UTC, Sivilenok commented on src/components/Header/styles.module.scss
> +      display: flex;
у меня уже замылился глаз просто

2023-02-22 19:16 UTC, Sivilenok commented on package.json
> +    "clsx": "^1.2.1",
сначала хотела, потом сделала по-другому)

2023-02-22 19:17 UTC, Sivilenok commented on src/components/MenuNav/styles.module.scss
> +      justify-content: space-between;
у меня не показывает дублирование никогда

2023-02-22 21:13 UTC, Sivilenok commented on src/components/MenuNav/styles.module.scss
> +  align-items: center;
изменила)

2023-02-22 22:06 UTC, Sivilenok commented on src/components/MenuNav/styles.module.scss
> +    width: 172px;
исправила

2023-02-22 22:07 UTC, Sivilenok commented on src/components/MenuNav/styles.module.scss
> +    background-color: #000000;
сделала

2023-02-22 22:07 UTC, Sivilenok commented on src/components/MenuNav/styles.module.scss
> +    @include breakpoint(md) {
удалила

2023-02-22 22:07 UTC, Sivilenok commented on src/components/MenuNav/styles.module.scss
> +      background: #4c4c4c;
исправила

2023-02-22 22:08 UTC, Sivilenok commented on src/components/MenuNav/styles.module.scss
> +      background: #b3b3b3;
исправила

2023-02-22 22:09 UTC, Sivilenok commented on package.json
> +    "styled-components": "^5.3.6",
спасибо за ревью)
так нужен или нет?)

2023-02-22 22:29 UTC, Sivilenok commented on package.json
> +    "styled-components": "^5.3.6",
удалила в общем)

2023-02-22 23:01 UTC, Sivilenok commented on src/hooks/useWindowSize.ts
> +  height: number | undefined;
okay

2023-02-22 23:31 UTC, Sivilenok commented on src/styles/shared/variables.ts
> +export enum BREAKPOINT {
исправила

2023-02-23 10:02 UTC, demyankov approved these changes

2023-02-23 15:33 UTC, merged