fix: shared button styles
Power-Rangers-3/Front-end pull request #62
Opened 2023-02-22 06:41 UTC by DimasAgeev

2023-02-22 07:14 UTC, demyankov requested changes

2023-02-22 07:14 UTC, demyankov commented on src/styles/shared/button.style.module.scss
> +    border-color: var(--border-color);
Если для active не предусмотрено отдельных стилей, то удали псевдокласс

2023-02-22 07:14 UTC, demyankov commented on src/styles/shared/button.style.module.scss
> +    background-color: var(--background-color-button-disabled);
для белой кнопки фон не меняется

2023-02-22 07:14 UTC, demyankov commented on src/styles/shared/button.style.module.scss
> +    color: var(--font-color-invert);
Зачем тут color. Измени цвет border. Или как вариант, для темной кнопки вообще убери border, чтобы не изменять его в цвет фона каждый раз

2023-02-22 07:14 UTC, demyankov commented on src/styles/shared/button.style.module.scss
> +    color: var(--font-color-invert);
Зачем тут color. Измени цвет border и background

2023-02-22 07:14 UTC, demyankov commented on src/styles/shared/button.style.module.scss
> +  &:disabled {
Убери color. Измени цвет border

2023-02-22 07:14 UTC, demyankov commented on src/styles/shared/button.style.module.scss
> +    color: var(--font-color-invert);
Убери color. Измени цвет border

2023-02-22 07:14 UTC, demyankov commented on src/styles/shared/button.style.module.scss
> +  &:focus {
Убери color. Измени цвет border и background

2023-02-22 07:14 UTC, demyankov commented on src/styles/shared/button.style.module.scss
> +  &:disabled {
Убери color. Измени цвет border

2023-02-22 09:00 UTC, andrey-kudinov commented on src/styles/shared/button.style.module.scss
> +  @extend %button;
Я не люблю фичу @extend так как из-за неё сильно разрастается скомпилированный файл со стилями
Как вариант - просто переиспользовать в вёрстке глобальный класс `.button`

2023-02-22 09:00 UTC, andrey-kudinov commented on src/styles/shared/button.style.module.scss
> +  @extend %button;
Коммент выше применим ко всем схожим местам

2023-02-24 06:44 UTC, andrey-kudinov commented on src/pages/HomePage/components/advantagesSection/advantagesSection.tsx
> +  <div className={styles.advantagesListElement}>
Здесь во всех местах у тебя есть слово `advantages`
Я думаю его можно смело удалить, потому что при дебаге в дев тулз и так будет видно по названию класса, что это за компонент
А тут в файлах для нас и так код выглядит читабельным и мы понимаем что это за стили

Других причин для сохранения такого длинного названия я не вижу

2023-02-24 06:44 UTC, andrey-kudinov commented on src/pages/HomePage/components/advantagesSection/advantagesSection.tsx
> +              <AdvantagesCard {...article} />
Здесь будет `key` ?

2023-02-24 06:46 UTC, andrey-kudinov commented on src/pages/HomePage/components/opportunitySection/opportunitySection.tsx
> +  <div className={styles.opportunityCard}>
opportunity можно смело выпилить из названия

причины теже самые что и выше
можем обсудить в тг подробнее, если есть сомнения

2023-02-24 06:47 UTC, andrey-kudinov commented on src/pages/HomePage/components/opportunitySection/opportunitySection.tsx
> +  <div className={styles.opportunityCard}>
а то иначе это подобие `БЭМ`, только вместо `__` просто `camelCase`

2023-02-24 08:29 UTC, demyankov approved these changes

2023-02-24 09:36 UTC, merged