fix bug: fix scroll pagination
Power-Rangers-3/Front-end pull request #92
Opened 2023-03-09 16:48 UTC by Sivilenok

2023-03-09 18:45 UTC, pyropetrick requested changes

2023-03-09 18:45 UTC, pyropetrick commented on src/pages/PlatformsPage/PlatformsPage.tsx
> +    document.addEventListener('click', handlePageChange);
шо це такое?

2023-03-09 18:45 UTC, pyropetrick commented on src/pages/PlatformsPage/PlatformsPage.tsx
> +    document.addEventListener('click', handlePageChange);
при таком раскладе будет любой клик вести вверх)

2023-03-09 19:14 UTC, Sivilenok commented on src/pages/PlatformsPage/PlatformsPage.tsx
> +    document.addEventListener('click', handlePageChange);
уже поняла, исправила, спасибо)

2023-03-09 19:43 UTC, pyropetrick approved these changes

2023-03-10 04:29 UTC, andrey-kudinov approved these changes

2023-03-12 17:22 UTC, merged